defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  docs:
    output: true
company_name: "Bestbrains"
company_member: "Bestbrainer"
company_members: "Bestbrainers"
company_cell: "Braincell"
company_cells: "Braincells"
company_board: "Koordinationsudvalget"
